env:
    MANIFEST: https://github.com/LineageOS/android.git -b lineage-17.1
    DEVICE: j7xelte
    OEM: samsung
    DT_PATH: device/$OEM/$DEVICE
    TARGET: bacon
    EXTRA_CMD: # git clone https://github.com/OrangeFoxRecovery/Avatar.git misc
    OUTPUT: *.zip
    LUNCH: lineage_j7xelte-eng

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
  
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/HoChiMinh /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - git config --global user.name "Sushrut1101"
       - git config --global user.email "guptasushrut@gmail.com"
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
  
  Neofetch_script:
       - neofetch
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 -u $MANIFEST 
      - repo sync -j16 --force-sync --no-tags --no-clone-bundle
      - git clone https://github.com/samsungexynos7870/android_device_samsung_universal7870-common.git -b lineage-17.1 device/samsung/universal7870-common
      - git clone https://github.com/samsungexynos7870/android_device_samsung_j7xelte.git -b crdroid device/samsung/j7xelte
      - git clone https://github.com/ping2109/NevaKernel-7870.git kernel/samsung/exynos7870
      - git clone https://github.com/samsungexynos7870/android_vendor_samsung_universal7870-common.git vendor/samsung/universal7870-common
      - git clone https://github.com/samsungexynos7870/android_vendor_samsung_j7xelte.git vendor/samsung/j7xelte
      - git clone https://github.com/samsungexynos7870/android_hardware_samsung.git -b lineage-17.1 hardware/samsung
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"
  
  
  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - . build/envsetup.sh
      - . $DT_PATH/vendorsetup.sh
      - lunch $LUNCH
      - make -j16 $TARGET
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
